version: "3"
services:
  ldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_HTTPS
      - PHPLDAPADMIN_LDAP_HOSTS
      - PHPLDAPADMIN_SERVER_ADMIN
      - PHPLDAPADMIN_SERVER_PATH
      - PHPLDAPADMIN_TRUST_PROXY_SSL
      - TZ
    networks:
      - public
    volumes:
      - ldapadmin_root:/var/www/phpldapadmin
    deploy:
      placement:
        constraints:
          - node.labels.frontend == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=traefik-public
        - traefik.http.services.ldapadmin.loadbalancer.server.port=80
        - traefik.http.routers.ldapadmin.rule=Host(`ldapadmin.example.org`)
        - traefik.http.routers.ldapadmin.service=ldapadmin
        - traefik.http.routers.ldapadmin.entrypoints=https
        - traefik.http.routers.ldapadmin.tls=true
        - traefik.http.routers.ldapadmin.tls.certresolver=letsencrypt

  authelia:
    image: authelia/authelia:latest
    environment:
      - TZ
    networks:
      - public
    volumes:
      - authelia_config:/config
    deploy:
      placement:
        constraints:
          - node.labels.frontend == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.example.org/
        - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
        - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email
        - traefik.http.services.authelia.loadbalancer.server.port=9091
        - traefik.http.routers.authelia.rule=Host(`authelia.example.org`)
        - traefik.http.routers.authelia.service=authelia
        - traefik.http.routers.authelia.entrypoints=https
        - traefik.http.routers.authelia.tls=true
        - traefik.http.routers.authelia.tls.certresolver=letsencrypt
        - traefik.http.routers.api.rule=Host(`traefik.example.org`)
        - traefik.http.routers.api.service=api@internal
        - traefik.http.routers.api.entrypoints=https
        - traefik.http.routers.api.tls=true
        - traefik.http.routers.api.tls.certresolver=letsencrypt
        - traefik.http.routers.api.middlewares=authelia@docker

networks:
  public:
    external: true

volumes:
  authelia_config:
    driver: local

  ldapadmin_root:
    driver: local
