theme: light
jwt_secret: CHANGEME
default_redirection_url: https://example.org/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false

log:
  level: info

totp:
  issuer: example.org
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 2m

  ldap:
    implementation: custom
    url: ldap://openldap
    timeout: 5s
    start_tls: false

    tls:
      skip_verify: false
      minimum_version: TLS1.2

    base_dn: dc=example,dc=org
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    user: cn=admin,dc=example,dc=org
    password: CHANGEME

access_control:
  default_policy: deny

  rules:
    - domain: traefik.example.org
      subject: "group:admins"
      policy: one_factor

session:
  name: example_org
  domain: example.org
  same_site: lax
  secret: insecure_session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

  redis:
    host: redis
    port: 6379
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: yourkey

  postgres:
    host: postgres
    port: 5432
    database: authelia
    username: authelia
    password: mypassword
    timeout: 5s
    sslmode: disable

notifier:
  disable_startup_check: false

  filesystem:
    filename: /config/notification.txt

  # smtp:
  #   host: 127.0.0.1
  #   port: 1025
  #   timeout: 5s
  #   username: test
  #   password: password
  #   sender: admin@example.com
  #   identifier: localhost
  #   subject: "[Authelia] {title}"
  #   startup_check_address: test@authelia.com
  #   disable_require_tls: false
  #   disable_html_emails: false

  #   tls:
  #     skip_verify: false
  #     minimum_version: TLS1.2
